apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rcg11u9is-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rcg11u9is-nodejs 
  name: rcg11u9is-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rcg11u9is-nodejs 
