apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rcg11u9is-nodejs 
  janus-idp.io/tekton: rcg11u9is-nodejs
  backstage.io/kubernetes-id: rcg11u9is-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rcg11u9is-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml