apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rcg11u9is-nodejs-gitops
  description: This is GitOps manifest for rcg11u9is-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rcg11u9is-nodejs
    backstage.io/kubernetes-id: rcg11u9is-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/rcg11u9is-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rcg11u9is-nodejs
